import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { ago, isSyntheticTask, jsonUnescape, lastMatch, readMeta } from "../src/claude";

describe("ago", () => {
  it("formats sub-minute, minutes, and hours", () => {
    const now = Date.now();
    expect(ago(now)).toBe("now");
    expect(ago(now - 5 * 60_000)).toBe("5m ago");
    expect(ago(now - 3 * 3_600_000)).toBe("3h ago");
  });
});

describe("isSyntheticTask", () => {
  it("flags Claude Code's injected/non-human turns", () => {
    for (const t of [
      "<synthetic>",
      "<command-name>/foo</command-name>",
      "<local-command-stdout>x</local-command-stdout>",
      "<bash-input>ls</bash-input>",
      "<system-reminder>note</system-reminder>",
      "<user-prompt-submit-hook>",
      "Caveat: The messages below were generated by the user while running a command",
    ]) {
      expect(isSyntheticTask(t)).toBe(true);
    }
  });

  it("treats a real human prompt as a task", () => {
    expect(isSyntheticTask("Please refactor the auth module")).toBe(false);
  });
});

describe("lastMatch", () => {
  it("returns the last capture", () => {
    expect(lastMatch('"m":"a" "m":"b" "m":"c"', /"m":"([^"]+)"/g)).toBe("c");
  });
  it("honors the accept predicate", () => {
    const v = lastMatch('"m":"real" "m":"<synthetic>"', /"m":"([^"]+)"/g, (x) => x !== "<synthetic>");
    expect(v).toBe("real");
  });
  it("returns undefined with no match", () => {
    expect(lastMatch("nothing", /"m":"([^"]+)"/g)).toBeUndefined();
  });
});

describe("jsonUnescape", () => {
  it("unescapes doubled backslashes (Windows paths)", () => {
    expect(jsonUnescape("C:\\\\Users\\\\me\\\\proj")).toBe("C:\\Users\\me\\proj");
  });
  it("leaves plain strings (and undefined) untouched", () => {
    expect(jsonUnescape("/Users/me/proj")).toBe("/Users/me/proj");
    expect(jsonUnescape(undefined)).toBeUndefined();
  });
  it("handles quotes and unicode escapes", () => {
    expect(jsonUnescape('a\\"b')).toBe('a"b');
    expect(jsonUnescape("\\u00a6")).toBe("¦");
  });
});

describe("readMeta", () => {
  let dir: string;
  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "devtower-meta-"));
  });
  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const write = (lines: object[]): { file: string; size: number } => {
    const file = path.join(dir, "session.jsonl");
    fs.writeFileSync(file, lines.map((l) => JSON.stringify(l)).join("\n") + "\n");
    return { file, size: fs.statSync(file).size };
  };

  it("reads cwd, model, last role, task, question, and context tokens", async () => {
    const cwd = path.join(dir, "proj");
    const { file, size } = write([
      { type: "user", cwd, message: { role: "user", content: "Fix the failing test" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          model: "claude-opus-4-8",
          content: [{ type: "text", text: "Which test file should I look at?" }],
          usage: { input_tokens: 100, cache_read_input_tokens: 40, cache_creation_input_tokens: 10 },
        },
      },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.cwd).toBe(cwd);
    expect(meta.launchCwd).toBe(cwd);
    expect(meta.model).toBe("claude-opus-4-8");
    expect(meta.lastRole).toBe("assistant");
    expect(meta.task).toBe("Fix the failing test");
    expect(meta.question).toContain("Which test file");
    expect(meta.contextTokens).toBe(150);
  });

  it("does not report a question when the last assistant turn is a statement", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "Ship it" } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "Done, pushed to main." }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.question).toBeUndefined();
  });

  it("ignores the <synthetic> model id", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "hi" } },
      { type: "assistant", message: { role: "assistant", model: "claude-sonnet-4-6", content: [{ type: "text", text: "ok" }] } },
      { type: "assistant", message: { role: "assistant", model: "<synthetic>", content: [{ type: "text", text: "x" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.model).toBe("claude-sonnet-4-6");
  });

  it("detects skills used via the Skill tool", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "review please" } },
      {
        type: "assistant",
        message: { role: "assistant", content: [{ type: "tool_use", name: "Skill", input: { skill: "code-review" } }] },
      },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.skills).toContain("code-review");
  });

  it("counts in-flight sub-agents (Task tool calls with no result yet)", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "fan out" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [
            { type: "tool_use", id: "toolu_1", name: "Task", input: {} },
            { type: "tool_use", id: "toolu_2", name: "Task", input: {} },
          ],
        },
      },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.subagents).toBe(2);
  });

  it("drops sub-agents from the count once their result returns", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "fan out" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [
            { type: "tool_use", id: "toolu_1", name: "Task", input: {} },
            { type: "tool_use", id: "toolu_2", name: "Agent", input: {} },
            { type: "tool_use", id: "toolu_3", name: "Task", input: {} },
          ],
        },
      },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_2", content: "done" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.subagents).toBe(2);
  });

  it("keeps a background sub-agent counted after its immediate launch ack", async () => {
    // a run_in_background Agent acks its launch right away ("agentId: …"); that
    // ack must NOT close the work — the agent is still running.
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "spawn in background" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [{ type: "tool_use", id: "toolu_bg", name: "Agent", input: { run_in_background: true } }],
        },
      },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_bg", content: "Async agent launched successfully.\nagentId: bg123abc" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.subagents).toBe(1);
  });

  it("drops a background sub-agent once its task-notification reports completion", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "spawn in background" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [{ type: "tool_use", id: "toolu_bg", name: "Agent", input: { run_in_background: true } }],
        },
      },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_bg", content: "Async agent launched successfully.\nagentId: bg123abc" }] } },
      { type: "user", message: { role: "user", content: "<task-notification>\n<task-id>bg123abc</task-id>\n<status>completed</status>\n</task-notification>" } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.subagents).toBe(0);
  });

  it("reports 0 sub-agents when none were spawned", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "hi" } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "ok" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.subagents).toBe(0);
  });

  it("unescapes a Windows-style cwd path (regression: backslash mangling)", async () => {
    const winCwd = "C:\\Users\\me\\proj";
    const { file, size } = write([
      { type: "user", cwd: winCwd, message: { role: "user", content: "hi" } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "ok" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.cwd).toBe(winCwd);
    expect(meta.launchCwd).toBe(winCwd);
  });

  it("returns {} for an unreadable file", async () => {
    const meta = await readMeta(path.join(dir, "missing.jsonl"), 100);
    expect(meta).toEqual({});
  });
});
