import { describe, it, expect, beforeEach, afterEach } from "vitest";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { ago, isSyntheticTask, jsonUnescape, lastMatch, readMeta } from "../src/claude";

describe("ago", () => {
  it("formats sub-minute, minutes, and hours", () => {
    const now = Date.now();
    expect(ago(now)).toBe("now");
    expect(ago(now - 5 * 60_000)).toBe("5m ago");
    expect(ago(now - 3 * 3_600_000)).toBe("3h ago");
  });
});

describe("isSyntheticTask", () => {
  it("flags Claude Code's injected/non-human turns", () => {
    for (const t of [
      "<synthetic>",
      "<command-name>/foo</command-name>",
      "<local-command-stdout>x</local-command-stdout>",
      "<bash-input>ls</bash-input>",
      "<system-reminder>note</system-reminder>",
      "<user-prompt-submit-hook>",
      "Caveat: The messages below were generated by the user while running a command",
    ]) {
      expect(isSyntheticTask(t)).toBe(true);
    }
  });

  it("treats a real human prompt as a task", () => {
    expect(isSyntheticTask("Please refactor the auth module")).toBe(false);
  });
});

describe("lastMatch", () => {
  it("returns the last capture", () => {
    expect(lastMatch('"m":"a" "m":"b" "m":"c"', /"m":"([^"]+)"/g)).toBe("c");
  });
  it("honors the accept predicate", () => {
    const v = lastMatch('"m":"real" "m":"<synthetic>"', /"m":"([^"]+)"/g, (x) => x !== "<synthetic>");
    expect(v).toBe("real");
  });
  it("returns undefined with no match", () => {
    expect(lastMatch("nothing", /"m":"([^"]+)"/g)).toBeUndefined();
  });
});

describe("jsonUnescape", () => {
  it("unescapes doubled backslashes (Windows paths)", () => {
    expect(jsonUnescape("C:\\\\Users\\\\me\\\\proj")).toBe("C:\\Users\\me\\proj");
  });
  it("leaves plain strings (and undefined) untouched", () => {
    expect(jsonUnescape("/Users/me/proj")).toBe("/Users/me/proj");
    expect(jsonUnescape(undefined)).toBeUndefined();
  });
  it("handles quotes and unicode escapes", () => {
    expect(jsonUnescape('a\\"b')).toBe('a"b');
    expect(jsonUnescape("\\u00a6")).toBe("¦");
  });
});

describe("readMeta", () => {
  let dir: string;
  beforeEach(() => {
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "devtower-meta-"));
  });
  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const write = (lines: object[]): { file: string; size: number } => {
    const file = path.join(dir, "session.jsonl");
    fs.writeFileSync(file, lines.map((l) => JSON.stringify(l)).join("\n") + "\n");
    return { file, size: fs.statSync(file).size };
  };

  it("reads cwd, model, last role, task, question, and context tokens", async () => {
    const cwd = path.join(dir, "proj");
    const { file, size } = write([
      { type: "user", cwd, message: { role: "user", content: "Fix the failing test" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          model: "claude-opus-4-8",
          content: [{ type: "text", text: "Which test file should I look at?" }],
          usage: { input_tokens: 100, cache_read_input_tokens: 40, cache_creation_input_tokens: 10 },
        },
      },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.cwd).toBe(cwd);
    expect(meta.launchCwd).toBe(cwd);
    expect(meta.model).toBe("claude-opus-4-8");
    expect(meta.lastRole).toBe("assistant");
    expect(meta.task).toBe("Fix the failing test");
    expect(meta.question).toContain("Which test file");
    expect(meta.contextTokens).toBe(150);
  });

  it("does not report a question when the last assistant turn is a statement", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "Ship it" } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "Done, pushed to main." }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.question).toBeUndefined();
  });

  it("ignores the <synthetic> model id", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "hi" } },
      { type: "assistant", message: { role: "assistant", model: "claude-sonnet-4-6", content: [{ type: "text", text: "ok" }] } },
      { type: "assistant", message: { role: "assistant", model: "<synthetic>", content: [{ type: "text", text: "x" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.model).toBe("claude-sonnet-4-6");
  });

  it("detects skills used via the Skill tool", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "review please" } },
      {
        type: "assistant",
        message: { role: "assistant", content: [{ type: "tool_use", name: "Skill", input: { skill: "code-review" } }] },
      },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.skills).toContain("code-review");
  });

  it("still detects a skill after >32KB of later output scrolls it past the tail window", async () => {
    // regression: skills were parsed from the 32KB tail only, so an active
    // session (a big `git pull`, file reads, a `gh run watch` dump) pushed the
    // skill signal out of the window within seconds and the borrow trip slipped
    // to the next incidental marker. Read over `full` instead, like sub-agents.
    const filler = "x".repeat(40 * 1024); // > the 32KB tail chunk
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "release please" } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "tool_use", name: "Skill", input: { skill: "release" } }] } },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", content: filler }] } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "done" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.skills).toContain("release");
  });

  it("counts in-flight sub-agents (Task tool calls with no result yet)", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "fan out" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [
            { type: "tool_use", id: "toolu_1", name: "Task", input: {} },
            { type: "tool_use", id: "toolu_2", name: "Task", input: {} },
          ],
        },
      },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.subagents).toBe(2);
  });

  it("drops sub-agents from the count once their result returns", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "fan out" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [
            { type: "tool_use", id: "toolu_1", name: "Task", input: {} },
            { type: "tool_use", id: "toolu_2", name: "Agent", input: {} },
            { type: "tool_use", id: "toolu_3", name: "Task", input: {} },
          ],
        },
      },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_2", content: "done" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.subagents).toBe(2);
  });

  it("keeps a background sub-agent counted after its immediate launch ack", async () => {
    // a run_in_background Agent acks its launch right away ("agentId: …"); that
    // ack must NOT close the work — the agent is still running.
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "spawn in background" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [{ type: "tool_use", id: "toolu_bg", name: "Agent", input: { run_in_background: true } }],
        },
      },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_bg", content: "Async agent launched successfully.\nagentId: bg123abc" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.subagents).toBe(1);
  });

  it("flags exploring while an Explore subagent is in flight", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "look into it" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [{ type: "tool_use", id: "toolu_x", name: "Task", input: { subagent_type: "Explore" } }],
        },
      },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.exploring).toBe(true);
  });

  it("clears exploring once the Explore subagent returns", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "look into it" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [{ type: "tool_use", id: "toolu_x", name: "Task", input: { subagent_type: "Explore" } }],
        },
      },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_x", content: "found it" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.exploring).toBe(false);
  });

  it("does not flag exploring for a non-Explore subagent", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "build it" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [{ type: "tool_use", id: "toolu_d", name: "Task", input: { subagent_type: "developer" } }],
        },
      },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.exploring).toBe(false);
  });

  it("flags exploring for a background Explore subagent until its task-notification", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "explore in background" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [{ type: "tool_use", id: "toolu_bgx", name: "Agent", input: { subagent_type: "Explore", run_in_background: true } }],
        },
      },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_bgx", content: "Async agent launched successfully.\nagentId: bgx99" }] } },
    ]);
    const live = await readMeta(file, size);
    expect(live.exploring).toBe(true);

    const { file: f2, size: s2 } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "explore in background" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [{ type: "tool_use", id: "toolu_bgx", name: "Agent", input: { subagent_type: "Explore", run_in_background: true } }],
        },
      },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_bgx", content: "Async agent launched successfully.\nagentId: bgx99" }] } },
      { type: "user", message: { role: "user", content: "<task-notification>\n<task-id>bgx99</task-id>\n<status>completed</status>\n</task-notification>" } },
    ]);
    const done = await readMeta(f2, s2);
    expect(done.exploring).toBe(false);
  });

  it("stamps prCreatedAt when a `gh pr create` command completes", async () => {
    const ts = "2026-06-14T17:30:00.000Z";
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "open a pr" } },
      {
        type: "assistant",
        message: { role: "assistant", content: [{ type: "tool_use", id: "toolu_pr", name: "Bash", input: { command: "gh pr create --fill" } }] },
      },
      { type: "user", timestamp: ts, message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_pr", content: "https://github.com/o/r/pull/42" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.prCreatedAt).toBe(Date.parse(ts));
  });

  it("stamps prClosedAt when a `gh pr merge` command completes", async () => {
    const ts = "2026-06-15T08:15:00.000Z";
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "merge it" } },
      {
        type: "assistant",
        message: { role: "assistant", content: [{ type: "tool_use", id: "toolu_m", name: "Bash", input: { command: "gh pr merge 23 --merge" } }] },
      },
      { type: "user", timestamp: ts, message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_m", content: "Merged" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.prClosedAt).toBe(Date.parse(ts));
  });

  it("stamps prClosedAt when a `gh pr close` command completes", async () => {
    const ts = "2026-06-15T08:20:00.000Z";
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "close it" } },
      {
        type: "assistant",
        message: { role: "assistant", content: [{ type: "tool_use", id: "toolu_c", name: "Bash", input: { command: "gh pr close 7" } }] },
      },
      { type: "user", timestamp: ts, message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_c", content: "Closed" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.prClosedAt).toBe(Date.parse(ts));
  });

  it("leaves prClosedAt undefined before the merge result lands", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "merge soon" } },
      {
        type: "assistant",
        message: { role: "assistant", content: [{ type: "tool_use", id: "toolu_m", name: "Bash", input: { command: "gh pr merge 23 --merge" } }] }, // emitted, not yet returned
      },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.prClosedAt).toBeUndefined();
  });

  it("leaves prCreatedAt undefined before the create result lands, and for other Bash commands", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "status then maybe a pr" } },
      {
        type: "assistant",
        message: { role: "assistant", content: [
          { type: "tool_use", id: "toolu_a", name: "Bash", input: { command: "git status" } },
          { type: "tool_use", id: "toolu_pr", name: "Bash", input: { command: "gh pr create --fill" } }, // emitted, not yet returned
        ] },
      },
      { type: "user", timestamp: "2026-06-14T17:30:00.000Z", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_a", content: "clean" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.prCreatedAt).toBeUndefined();
  });

  it("drops a background sub-agent once its task-notification reports completion", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "spawn in background" } },
      {
        type: "assistant",
        message: {
          role: "assistant",
          content: [{ type: "tool_use", id: "toolu_bg", name: "Agent", input: { run_in_background: true } }],
        },
      },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "toolu_bg", content: "Async agent launched successfully.\nagentId: bg123abc" }] } },
      { type: "user", message: { role: "user", content: "<task-notification>\n<task-id>bg123abc</task-id>\n<status>completed</status>\n</task-notification>" } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.subagents).toBe(0);
  });

  it("reports 0 sub-agents when none were spawned", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "hi" } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "ok" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.subagents).toBe(0);
  });

  it("flags working when a tool is in flight (assistant tool_use is the newest record)", async () => {
    // a long-running Bash (build/test/screenshots) leaves an assistant tool_use at
    // the tail with no result yet — the session is working, not idle.
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "run the screenshots" } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "tool_use", id: "t1", name: "Bash", input: { command: "npm run screenshots" } }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.working).toBe(true);
  });

  it("flags working when the agent owes a reply (newest record is a user tool_result)", async () => {
    // a long model turn: the prior tool_result is the tail and the agent hasn't
    // written its next turn yet — still working.
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "do it" } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "tool_use", id: "t1", name: "Bash", input: { command: "git status" } }] } },
      { type: "user", message: { role: "user", content: [{ type: "tool_result", tool_use_id: "t1", content: "clean" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.working).toBe(true);
  });

  it("does NOT flag working when the newest turn is a finished assistant statement", async () => {
    const { file, size } = write([
      { type: "user", cwd: dir, message: { role: "user", content: "ship it" } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "Done, pushed to main." }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.working).toBe(false);
  });

  it("unescapes a Windows-style cwd path (regression: backslash mangling)", async () => {
    const winCwd = "C:\\Users\\me\\proj";
    const { file, size } = write([
      { type: "user", cwd: winCwd, message: { role: "user", content: "hi" } },
      { type: "assistant", message: { role: "assistant", content: [{ type: "text", text: "ok" }] } },
    ]);
    const meta = await readMeta(file, size);
    expect(meta.cwd).toBe(winCwd);
    expect(meta.launchCwd).toBe(winCwd);
  });

  it("returns {} for an unreadable file", async () => {
    const meta = await readMeta(path.join(dir, "missing.jsonl"), 100);
    expect(meta).toEqual({});
  });
});
